### PR TITLE
java|js|rust|ruby

### PR DESCRIPTION
**Pull request by Anuraj-IND**
# Pull Request Template

## Description

Please include a summary of the changes and the language you are adding or modifying. 

## Checklist

- [x] My code follows the project's coding style and guidelines.
- [x] I have tested my implementation to ensure it works as expected.
- [x] I have included a `Makefile` if applicable.
- [x] I have added a README file for the new language implementation.
- [x] I have updated the `.github/workflows/test.yml` file to include the new language in the list of languages to test.
- [x] I have included any dependencies required for the new language implementation in the test workflow.
- [x] I have reviewed and understood the code before submitting (for AI-generated submissions).

## Related Issue

Please link to any related issues here.

## Type of Change

- New language implementation(added java,js,ruby and rust)
- [ ] Bug fix
- [x] Documentation update
- [ ] Other (please describe):

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 

## Screenshots (if applicable)

If applicable, add screenshots to help explain your changes.

## Additional Information

Add any other information about your pull request here.

## Contributing

To contribute to this project, please see the [CONTRIBUTING.md](/.github/CONTRIBUTING.md) file.

## License

This project is licensed under the MIT License. For more information, please see the [LICENSE](/LICENSE) file.

### CODE REVIEW

**Comment by Anuraj-IND** [comment]
respond to it please its my first contribution if i did something wrong clarify me ill improve that

**Comment by zachflower** [comment]
@Anuraj-IND this project is primarily intended for the students of a high school computer science and cybersecurity class to practice open source contributions through the lens of Hacktoberfest. I'll accept yours and other contributions later in the month, but my students currently get the priority.

**Comment by Anuraj-IND** [comment]
> @Anuraj-IND this project is primarily intended for the students of a high school computer science and cybersecurity class to practice open source contributions through the lens of Hacktoberfest. I'll accept yours and other contributions later in the month, but my students currently get the priority.

sir im also a student please i just want one contribution here please :( unlike em i dont have a teacher i have to study from youtube let this one slide and accept it

**Review by Anuraj-IND — COMMENTED** [review]
Checked

**Comment by Anuraj-IND** [comment]
@zachflower sir its almost end of october i want one more pull accept can you help me ?

**Pull request closed without merging**
